# Generated by Django 3.2.5 on 2021-07-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ISPN', models.IntegerField(blank=True, null=True)),
                ('publisherYear', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('avalible', 'avalible'), ('borrowed', 'borrowed')], max_length=50, null=True)),
                ('photo_book', models.ImageField(blank=True, null=True, upload_to='Photo')),
                ('borrowing_price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('borrowing_period', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
