# Generated by Django 3.2.5 on 2021-07-20 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20210714_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Role',
        ),
        migrations.AddField(
            model_name='student',
            name='User',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default=datetime.datetime(2021, 7, 20, 17, 47, 28, 921327, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
