# Generated by Django 3.2.5 on 2021-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20210720_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=25)),
                ('Lname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phoneNum', models.CharField(max_length=11)),
                ('Bdate', models.DateField(blank=True)),
                ('User', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='admin', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='Gender',
        ),
    ]
